### ISSUE TITLE
使用 METEORUP_LANG=zh_CN 部署时报错

### ISSUE THREAD

**Issue by lzl** [romejiang/meteorup#7]
- 操作系统为 macOS 10.12.1 英文版。
- Meteorup 版本号为 2.0.0-alpha2.

```
if (process.env.LANG.indexOf('zh') > -1) defaultLocale = 'zh_CN';
                    ^

TypeError: Cannot read property 'indexOf' of undefined
    at Object.<anonymous> (/Users/lizunlong/.nvm/versions/node/v5.10.1/lib/node_modules/meteorup/bin/meteorup:11:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

**Comment by romejiang** [comment]
是个bug，应该是没有做变量不存在的检查，随后改。暂时你可以在环境变量里设置一个默认值解决这个问题。

如果你是英文系统：
   export LANG=en
如果是中文
   export LANG=zh_CN
