### ISSUE TITLE
可以支持在windows环境下进行部署吗

### ISSUE THREAD

**Issue by FrankLiu** [romejiang/meteorup#8]
我的本地运行环境是windows + gitbash， 远程服务器是linux，当我调用meteorup push -s 的时候出现下面的错误。
想知道在windows下是否可以支持？如果暂时不能支持，有支持的计划吗？

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn meteor ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by romejiang** [comment]
不支持windows环境下部署，也没有计划支持windows的版本。因为用了到一些机制比如ssh认证等在windows都无法实现。

看你这个报错信息是内存不足引起的错误。所以你可以检查一下内存的情况。

建议：你可以Cygwin ，在windows环境下模拟linux。当然最好还是迁移到linux或者mac环境下开发😊

**Comment by FrankLiu** [comment]
哥，我用npm安装的版本是1.0.17，我改了一下，经过测试，目前可以支持在Windows下的gitbash和cygwin的发布了，具体的修改部分如下：

只需要修改lib/build.js文件即可
文件头增加导入readline模块：
var readline = require('readline');

44行增加shell参数：var options = {cwd: appPath, shell: true};

74行：process.stdout.cursor(0) 修改为 readline.cursorTo(process.stdout, 0);
76行：process.stdout.clearLine(1) 修改为 readline.clearLine(process.stdout, 1);

83行：process.stdout.clearLine() 修改为 readline.clearLine(process.stdout, 1);
84行：process.stdout.cursorTo(0) 修改为 readline.cursorTo(process.stdout, 0);

目前在我本地测试都是可以工作的，请考虑一下是否可以加入到版本库里头。

**Comment by romejiang** [comment]
好的，我测试后merge进入。谢谢！
